/**
 * foods.js — Initial food dataset for ATE
 * 24 foods with full taste profiles, pricing, and metadata
 */

const INITIAL_FOODS = [
  {
    id: 1,
    name: "Nasi Lemak",
    emoji: "🍚",
    image: "",
    price: 8,
    category: "Rice",
    tastes: { sweet: 2, salty: 4, sour: 1, bitter: 0, spicy: 3, savory: 5 },
    spicyLevel: "medium",
    mealSize: "heavy",
    distance: 1.2,
    location: "Nearby Food Court",
    description: "Fragrant coconut rice served with sambal, egg, peanuts and anchovies. A true Malaysian classic.",
    isUserCreated: false
  },
  {
    id: 2,
    name: "Nasi Ayam",
    emoji: "🍗",
    image: "",
    price: 9,
    category: "Rice",
    tastes: { sweet: 1, salty: 4, sour: 0, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "mild",
    mealSize: "normal",
    distance: 0.8,
    location: "Chicken Rice Stall",
    description: "Tender poached or roasted chicken served over fragrant rice with chilli sauce and ginger paste.",
    isUserCreated: false
  },
  {
    id: 3,
    name: "Ayam Penyet",
    emoji: "🍗",
    image: "",
    price: 12,
    category: "Rice",
    tastes: { sweet: 1, salty: 4, sour: 1, bitter: 0, spicy: 5, savory: 5 },
    spicyLevel: "very-spicy",
    mealSize: "heavy",
    distance: 1.5,
    location: "Indonesian Warung",
    description: "Crispy smashed fried chicken served with fiery sambal, tempeh, tofu and steamed rice.",
    isUserCreated: false
  },
  {
    id: 4,
    name: "Nasi Goreng",
    emoji: "🍳",
    image: "",
    price: 9,
    category: "Rice",
    tastes: { sweet: 2, salty: 5, sour: 0, bitter: 0, spicy: 2, savory: 5 },
    spicyLevel: "mild",
    mealSize: "normal",
    distance: 0.5,
    location: "Mamak Corner",
    description: "Wok-fried rice with egg, soy sauce and aromatic spices. A satisfying any-time-of-day meal.",
    isUserCreated: false
  },
  {
    id: 5,
    name: "Mee Goreng",
    emoji: "🍜",
    image: "",
    price: 8,
    category: "Noodles",
    tastes: { sweet: 3, salty: 4, sour: 1, bitter: 0, spicy: 3, savory: 4 },
    spicyLevel: "medium",
    mealSize: "normal",
    distance: 0.5,
    location: "Mamak Corner",
    description: "Spicy stir-fried yellow noodles with egg, vegetables and a tangy-sweet sauce.",
    isUserCreated: false
  },
  {
    id: 6,
    name: "Maggi Goreng",
    emoji: "🍜",
    image: "",
    price: 6,
    category: "Noodles",
    tastes: { sweet: 2, salty: 5, sour: 0, bitter: 0, spicy: 2, savory: 4 },
    spicyLevel: "mild",
    mealSize: "light",
    distance: 0.4,
    location: "24hr Mamak",
    description: "Late-night comfort classic — fried instant noodles with egg, veggies, and chilli.",
    isUserCreated: false
  },
  {
    id: 7,
    name: "Tom Yum",
    emoji: "🍲",
    image: "",
    price: 14,
    category: "Other",
    tastes: { sweet: 2, salty: 3, sour: 5, bitter: 1, spicy: 4, savory: 4 },
    spicyLevel: "very-spicy",
    mealSize: "normal",
    distance: 2.0,
    location: "Thai Restaurant",
    description: "Fiery, sour and aromatic Thai soup loaded with mushrooms, lemongrass and prawns.",
    isUserCreated: false
  },
  {
    id: 8,
    name: "Laksa",
    emoji: "🍜",
    image: "",
    price: 11,
    category: "Noodles",
    tastes: { sweet: 2, salty: 4, sour: 2, bitter: 0, spicy: 4, savory: 5 },
    spicyLevel: "medium",
    mealSize: "heavy",
    distance: 1.8,
    location: "Laksa Stall",
    description: "Rich and creamy spicy coconut noodle soup — bold, fragrant and deeply satisfying.",
    isUserCreated: false
  },
  {
    id: 9,
    name: "Asam Laksa",
    emoji: "🍜",
    image: "",
    price: 10,
    category: "Noodles",
    tastes: { sweet: 1, salty: 3, sour: 5, bitter: 1, spicy: 3, savory: 3 },
    spicyLevel: "medium",
    mealSize: "normal",
    distance: 3.0,
    location: "Heritage Hawker",
    description: "Tangy tamarind-based fish noodle soup with pineapple, mint and shrimp paste.",
    isUserCreated: false
  },
  {
    id: 10,
    name: "Ramen",
    emoji: "🍜",
    image: "",
    price: 18,
    category: "Japanese",
    tastes: { sweet: 1, salty: 4, sour: 0, bitter: 0, spicy: 2, savory: 5 },
    spicyLevel: "mild",
    mealSize: "heavy",
    distance: 2.5,
    location: "Japanese Noodle Bar",
    description: "Rich tonkotsu or shoyu broth with chewy noodles, chashu pork, soft egg and nori.",
    isUserCreated: false
  },
  {
    id: 11,
    name: "Burger",
    emoji: "🍔",
    image: "",
    price: 13,
    category: "Fast Food",
    tastes: { sweet: 2, salty: 4, sour: 1, bitter: 0, spicy: 1, savory: 4 },
    spicyLevel: "not-spicy",
    mealSize: "normal",
    distance: 1.0,
    location: "Burger Stall",
    description: "Juicy beef patty with melted cheese, fresh lettuce, tomato and special sauce.",
    isUserCreated: false
  },
  {
    id: 12,
    name: "Pizza",
    emoji: "🍕",
    image: "",
    price: 22,
    category: "Western",
    tastes: { sweet: 2, salty: 4, sour: 2, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "not-spicy",
    mealSize: "normal",
    distance: 2.0,
    location: "Pizza Place",
    description: "Hand-stretched pizza with tangy tomato sauce, mozzarella and your favourite toppings.",
    isUserCreated: false
  },
  {
    id: 13,
    name: "Sushi",
    emoji: "🍣",
    image: "",
    price: 30,
    category: "Japanese",
    tastes: { sweet: 2, salty: 3, sour: 3, bitter: 0, spicy: 1, savory: 4 },
    spicyLevel: "mild",
    mealSize: "normal",
    distance: 3.5,
    location: "Japanese Restaurant",
    description: "Delicate rolls and nigiri with fresh fish, vinegared rice, wasabi and pickled ginger.",
    isUserCreated: false
  },
  {
    id: 14,
    name: "Pasta",
    emoji: "🍝",
    image: "",
    price: 19,
    category: "Western",
    tastes: { sweet: 1, salty: 3, sour: 2, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "not-spicy",
    mealSize: "normal",
    distance: 2.8,
    location: "Italian Café",
    description: "Al-dente pasta tossed in rich tomato or creamy sauce with herbs and parmesan.",
    isUserCreated: false
  },
  {
    id: 15,
    name: "Chicken Chop",
    emoji: "🍗",
    image: "",
    price: 16,
    category: "Western",
    tastes: { sweet: 1, salty: 4, sour: 1, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "not-spicy",
    mealSize: "heavy",
    distance: 2.0,
    location: "Western Food Stall",
    description: "Grilled or fried chicken leg quarter with mushroom sauce, fries and coleslaw.",
    isUserCreated: false
  },
  {
    id: 16,
    name: "Satay",
    emoji: "🍢",
    image: "",
    price: 10,
    category: "Snack",
    tastes: { sweet: 4, salty: 3, sour: 1, bitter: 0, spicy: 2, savory: 4 },
    spicyLevel: "mild",
    mealSize: "light",
    distance: 1.0,
    location: "Night Market",
    description: "Grilled marinated meat skewers with a rich peanut dipping sauce and ketupat.",
    isUserCreated: false
  },
  {
    id: 17,
    name: "Roti Canai",
    emoji: "🫓",
    image: "",
    price: 4,
    category: "Other",
    tastes: { sweet: 1, salty: 2, sour: 0, bitter: 0, spicy: 0, savory: 3 },
    spicyLevel: "not-spicy",
    mealSize: "light",
    distance: 0.4,
    location: "24hr Mamak",
    description: "Flaky, crispy flatbread served with dhal or curry — a Malaysian breakfast staple.",
    isUserCreated: false
  },
  {
    id: 18,
    name: "Cendol",
    emoji: "🍧",
    image: "",
    price: 5,
    category: "Dessert",
    tastes: { sweet: 5, salty: 1, sour: 0, bitter: 0, spicy: 0, savory: 0 },
    spicyLevel: "not-spicy",
    mealSize: "light",
    distance: 0.6,
    location: "Dessert Stall",
    description: "Icy shaved ice dessert with pandan jelly, red beans and rich gula melaka syrup.",
    isUserCreated: false
  },
  {
    id: 19,
    name: "Ice Cream",
    emoji: "🍦",
    image: "",
    price: 6,
    category: "Dessert",
    tastes: { sweet: 5, salty: 0, sour: 0, bitter: 0, spicy: 0, savory: 0 },
    spicyLevel: "not-spicy",
    mealSize: "light",
    distance: 0.8,
    location: "Ice Cream Parlour",
    description: "Creamy scoops in your favourite flavour — vanilla, chocolate, strawberry or more.",
    isUserCreated: false
  },
  {
    id: 20,
    name: "Waffle",
    emoji: "🧇",
    image: "",
    price: 8,
    category: "Dessert",
    tastes: { sweet: 4, salty: 1, sour: 0, bitter: 0, spicy: 0, savory: 1 },
    spicyLevel: "not-spicy",
    mealSize: "light",
    distance: 1.5,
    location: "Café",
    description: "Crispy golden waffles topped with butter, syrup, ice cream or fresh fruit.",
    isUserCreated: false
  },
  {
    id: 21,
    name: "Takoyaki",
    emoji: "🐙",
    image: "",
    price: 9,
    category: "Japanese",
    tastes: { sweet: 2, salty: 3, sour: 1, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "not-spicy",
    mealSize: "light",
    distance: 2.2,
    location: "Japanese Street Stall",
    description: "Crispy-outside, gooey-inside octopus balls drizzled with takoyaki sauce and mayo.",
    isUserCreated: false
  },
  {
    id: 22,
    name: "Salted Egg Chicken",
    emoji: "🍗",
    image: "",
    price: 15,
    category: "Other",
    tastes: { sweet: 1, salty: 5, sour: 0, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "mild",
    mealSize: "normal",
    distance: 1.8,
    location: "Fusion Stall",
    description: "Crispy fried chicken coated in a rich, buttery salted egg yolk sauce — addictively good.",
    isUserCreated: false
  },
  {
    id: 23,
    name: "Fish and Chips",
    emoji: "🐟",
    image: "",
    price: 17,
    category: "Western",
    tastes: { sweet: 0, salty: 4, sour: 2, bitter: 0, spicy: 0, savory: 4 },
    spicyLevel: "not-spicy",
    mealSize: "heavy",
    distance: 3.0,
    location: "British Café",
    description: "Beer-battered crispy fish fillet with thick-cut chips, mushy peas and tartar sauce.",
    isUserCreated: false
  },
  {
    id: 24,
    name: "Chicken Rice",
    emoji: "🍗",
    image: "",
    price: 10,
    category: "Rice",
    tastes: { sweet: 1, salty: 4, sour: 0, bitter: 0, spicy: 1, savory: 5 },
    spicyLevel: "mild",
    mealSize: "normal",
    distance: 1.0,
    location: "Hainanese Chicken Rice",
    description: "Silky Hainanese-style chicken with fragrant sesame rice, clear soup and dipping sauces.",
    isUserCreated: false
  }
];
